export AIRFLOW_HOME=/etc/airflow
export PYTHONPATH=/etc/airflow/custom_py:$AIRFLOW_HOME/google-api-python-client
export GOOGLE_APPLICATION_CREDENTIALS=/etc/airflow/gce-airflow-key.json
export PROJECT_NAME={GOOGLE_CLOUD_PROJECT}
export BUCKET_NAME={GOOGLE_CLOUD_PROJECT}-dataflow
